/* Copyright 2020 UPMEM. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

#ifndef UFI_DPU_QUERY_TYPE_H
#define UFI_DPU_QUERY_TYPE_H

#define DPU_QUERY_TYPE_NAME(query_type)                                                                                          \
    ((((uint32_t)(query_type)) < NR_OF_DPU_QUERY_TYPES) ? dpu_query_type_names[query_type] : "DPU_QUERY_TYPE_UNKNOWN")

typedef enum _dpu_query_type_e {
    DPU_QUERY_IGNORED = 0,
    DPU_QUERY_BIT_ORDER = 1,
    DPU_QUERY_IDENTITY = 2,
    DPU_QUERY_SOFTWARE_RESET = 3,
    DPU_QUERY_THERMAL_CONFIGURATION = 4,
    DPU_QUERY_COMMAND_DURATION_CONFIGURATION = 5,
    DPU_QUERY_RESULT_DURATION_CONFIGURATION = 6,
    DPU_QUERY_RESULT_SAMPLING_CONFIGURATION = 7,
    DPU_QUERY_BYTE_ORDER = 8,
    DPU_QUERY_NOP = 9,
    DPU_QUERY_SELECT_DPU = 10,
    DPU_QUERY_SELECT_GROUP = 11,
    DPU_QUERY_SELECT_ALL = 12,
    DPU_QUERY_WRITE_GROUP = 13,
    DPU_QUERY_READ_DMA_CONTROL = 14,
    DPU_QUERY_WRITE_DMA_CONTROL = 15,
    DPU_QUERY_CLEAR_DMA_CONTROL = 16,
    DPU_QUERY_READ_DMA_FAULT_THREAD_INDEX = 17,
    DPU_QUERY_READ_BKP_FAULT_THREAD_INDEX = 18,
    DPU_QUERY_READ_MEM_FAULT_THREAD_INDEX = 19,
    DPU_QUERY_READ_PC_LSB = 20,
    DPU_QUERY_READ_PC_MSB = 21,
    DPU_QUERY_READ_PC_MODE = 22,
    DPU_QUERY_WRITE_PC_MODE = 23,
    DPU_QUERY_READ_DPU_FAULT_STATE = 24,
    DPU_QUERY_CLEAR_DPU_FAULT_STATE = 25,
    DPU_QUERY_SET_AND_STEP_DPU_FAULT_STATE = 26,
    DPU_QUERY_READ_DPU_RUN_STATE = 27,
    DPU_QUERY_READ_BKP_FAULT = 28,
    DPU_QUERY_CLEAR_BKP_FAULT = 29,
    DPU_QUERY_SET_BKP_FAULT = 30,
    DPU_QUERY_READ_POISON_FAULT = 31,
    DPU_QUERY_CLEAR_POISON_FAULT = 32,
    DPU_QUERY_SET_POISON_FAULT = 33,
    DPU_QUERY_READ_AND_CLEAR_DMA_FAULT = 34,
    DPU_QUERY_READ_AND_CLEAR_MEM_FAULT = 35,
    DPU_QUERY_READ_AND_CLEAR_STACK_UP = 36,
    DPU_QUERY_READ_AND_SET_STACK_UP = 37,
    DPU_QUERY_BOOT_THREAD = 38,
    DPU_QUERY_RESUME_THREAD = 39,
    DPU_QUERY_CLEAR_RUN_THREAD = 40,
    DPU_QUERY_READ_RUN_THREAD = 41,
    DPU_QUERY_WRITE_IRAM_INSTRUCTION = 42,
    DPU_QUERY_READ_IRAM_INSTRUCTION = 43,
    DPU_QUERY_WRITE_WRAM_WORD = 44,
    DPU_QUERY_READ_WRAM_WORD = 45,
    DPU_QUERY_IREPAIR_AB_CONFIGURATION = 46,
    DPU_QUERY_IREPAIR_CD_CONFIGURATION = 47,
    DPU_QUERY_IREPAIR_OE_CONFIGURATION = 48,
    DPU_QUERY_REGISTER_FILE_TIMING_CONFIGURATION = 49,
    DPU_QUERY_COMMAND_BUS_DURATION_CONFIGURATION = 50,
    DPU_QUERY_COMMAND_BUS_SAMPLING_CONFIGURATION = 51,
    DPU_QUERY_COMMAND_BUS_SYNCHRONIZATION = 52,
    DPU_QUERY_RESULT_BUS_DURATION_CONFIGURATION = 53,
    DPU_QUERY_RESULT_BUS_SYNCHRONIZATION = 54,
    DPU_QUERY_READ_NOTIFY_BIT = 55,
    DPU_QUERY_READ_AND_CLEAR_NOTIFY_BIT = 56,
    DPU_QUERY_READ_AND_SET_NOTIFY_BIT = 57,
    DPU_QUERY_DEBUG_STD_REPLACE_STOP_ENABLED = 58,
    DPU_QUERY_DEBUG_STD_REPLACE_CLEAR = 59,
    DPU_QUERY_DEBUG_STD_SAMPLE_PC = 60,

    NR_OF_DPU_QUERY_TYPES = 61
} dpu_query_type_e;

extern const char *dpu_query_type_names[NR_OF_DPU_QUERY_TYPES];

#endif /* UFI_DPU_QUERY_TYPE_H */
